language: objective-c
osx_image: xcode7.3
env:
  - MODE=OSXCore CFG=Debug
  - MODE=OSXCore CFG=Release
  - MODE=iOSCore CFG=Debug
  - MODE=iOSCore CFG=Release
  - MODE=Example_BloggerSample CFG=Both
  - MODE=Example_DriveSample CFG=Both
  - MODE=Example_TasksSample CFG=Both
script:
  - ./.travis.sh "${MODE}" "${CFG}"
notifications:
  email: false
